### ISSUE TITLE
[9.0] Install Base Currency Inverse Rate rounding error

### ISSUE THREAD

**Issue by augustosamame** [ingadhoc/account-financial-tools#36]
Hi. I have installed this module and when setting the inverse rate, a rounding error is introduced. It happens with nice round numbers, which is unexpected:

I am setting 3.400 PEN (my default currency) per 1 USD

Now, when I create an invoice or vendor bill for USD 1000, the Accounting shows it as PEN 3399.99

This affects payments and reports and is driving everybody nuts.
Any help is appreciated

**Comment by jjscarafia** [comment]
This happens because currency is still expressed in default odoo way and due to digits precision. You can try using PEN as base currency (1) and setting USD exchange 3400 or viceversa.
There is also some module in the oca or not sure where, that changes odoo behaviour, in the way it can suits you but I don't remember where I have seen it.
